Repository panjf2000/ants, pull requests merged in 2023-07, with the labels that each got.

#285 feat: add a new API `ReleaseTimeout` for the default pool
  ants.go
  ants_test.go
Labels: enhancement, pending merged, proposal, accepted, new feature

#286 ver: release v2.8.0
  .github/workflows/codeql.yml
  .github/workflows/test.yml
  ants.go
  ants_test.go
Labels: minor

#287 opt: fix the potential goroutine leak after calling `Release()`
  pool.go
  pool_func.go
Labels: enhancement, waiting for response, pending development, accepted, optimization, needs fix

#288 ver: release v2.8.1
  pool.go
  pool_func.go
Labels: patch

#290 chore: add a new use case
  README.md
  README_ZH.md
Labels: new feature, docs
