Repository panjf2000/ants, pull requests merged in 2023-09, with the labels that each got.

#295 refactor: refine the code in `retrieveWorker` to make it more readable
  pool.go
  pool_func.go
Labels: waiting for response, pending development, optimization

#297 bug: return the error from Pool.Submit/PoolWithFunc.Invoke accordingly
  pool.go
  pool_func.go
Labels: bug

#300 chore: enable more title matchers for auto-labelers of bug and new feature
  .github/release-drafter.yml
Labels: chores

#299 patch: v2.8.2
  .github/release-drafter.yml
  .github/workflows/test.yml
  README.md
  README_ZH.md
  go.mod
  go.sum
  pool.go
  pool_func.go
Labels: bug, docs, patch
