Repository panjf2000/ants, pull requests merged in 2023-11, with the labels that each got.

#305 feat: add MultiPool and MultiPoolWithFunc
  ants.go
  ants_benchmark_test.go
  ants_test.go
  multipool.go
  multipool_func.go
  pool.go
  pool_func.go
Labels: enhancement, proposal, pending development, new feature

#307 ver: release 2.9.0
  .github/pull_request_template.md
  ants.go
  ants_benchmark_test.go
  ants_test.go
  multipool.go
  multipool_func.go
  pool.go
  pool_func.go
  worker_loop_queue.go
  worker_stack.go
Labels: minor

#309 chore: add new benchmark tests
  ants_benchmark_test.go
Labels: chores

#311 doc: add MultiPool & MultiPoolFunc example code and update READMEs.
  README.md
  README_ZH.md
  examples/main.go
Labels: pending merged, chores, docs
